name: Deploy docs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    timeout-minutes: 10

    steps:
    - name: Check out code repository
      uses: actions/checkout@v2
      with:
        path:  github-actions-cicd-example

    - name: Check out docs repository
      uses: actions/checkout@v2
      with:
        repository: alexmalins/alexmalins.github.io
        path: alexmalins.github.io
        token: ${{secrets.PUSH_TOKEN}}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd  github-actions-cicd-example
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_docs.txt

    - name: Build docs
      run: |
        cd github-actions-cicd-example/docs
        make html

    - name: Push docs
      run: |
        cp -RT  github-actions-cicd-example/docs/build/html alexmalins.github.io/doc/github-actions-cicd-example
        cd alexmalins.github.io
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Documentation update"
        git push https:://$USERNAME:$REPO_KEY@github.com/alexmalins/alexmalins.github.io.git
      env:
        REPO_KEY: ${{secrets.PUSH_TOKEN}}
        USERNAME: github-actions[bot]
